CREATE TABLE IF NOT EXISTS dentistas(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(255) NOT NULL,
sobrenome VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS endereco(
id INT AUTO_INCREMENT PRIMARY KEY,
rua VARCHAR(255) NOT NULL,
numero INT NOT NULL,
bairro VARCHAR(100) NOT NULL,
cidade VARCHAR(100) NOT NULL,
estado VARCHAR(100) NOT NULL
)